TWEAK_NAME = HoYosphere
HoYosphere_FILES = Time.m ControlCenter.m Passcode.m
HoYosphere_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN
HoYosphere_FRAMEWORKS = UIKit CoreText

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
