BUNDLE_NAME = HoYospherePreferences
HoYospherePreferences_FILES = $(wildcard Controllers/*.m Cells/*.m)
HoYospherePreferences_FRAMEWORKS = UIKit
HoYospherePreferences_PRIVATE_FRAMEWORKS = Preferences
HoYospherePreferences_INSTALL_PATH = /Library/PreferenceBundles
HoYospherePreferences_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
